@Backend_HostAddress = http://localhost:5051

### Basic Health Check
GET {{Backend_HostAddress}}/hell-thy
Accept: application/json

### Create a Ticket
POST {{Backend_HostAddress}}/api/Ticket
Content-Type: application/json

{
  "Title": "Some Dummy Title",
  "Description": "Some dummy description",
  "Priority": 1
}

### Get ticket
GET {{Backend_HostAddress}}/api/Ticket/5eaff326-9e5f-407c-82fa-424dae27998c
Accept: application/json
